trigger:
- main

pool:
  name: Default  # Using your self-hosted agent pool

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '21'  # Install JDK 21
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'AzureStorage'  # Change to 'PreInstalled' if JDK 21 is already installed

- task: Maven@3
  inputs:
    mavenPomFile: './prgm2-example-jar/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkVersionOption: '21'  # Updated to use JDK 21
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'