trigger:
- main

pool:
  name: Default  # Using your self-hosted agent pool

steps:
- script: |
    echo "Setting JAVA_HOME"
    set JAVA_HOME=C:\Program Files\Java\jdk-21
    echo JAVA_HOME is set to %JAVA_HOME%
  displayName: 'Set JAVA_HOME'

- task: Maven@3
  inputs:
    mavenPomFile: './prgm2-example-jar/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkDirectory: 'C:\Program Files\Java\jdk-21'  # Explicitly set JDK path
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'